FROM tomcat:8-jre8 

# Copy to images tomcat path 
# ADD web.xml /usr/local/tomcat/conf/ 
# ADD obclient.properties /etc/ 
# ADD WebClient.properties /etc/ 
# ADD yourwarfile.war /usr/local/tomcat/webapps/ 

# To set the username and password to access Tomcat admin page. 
# You can add settings.xml and tomcat-users.xml 

# ADD settings.xml /usr/local/tomcat/conf/
# ADD tomcat-users.xml /usr/local/tomcat/conf/


